spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.datasource.platform: postgres
spring.datasource.url: jdbc:postgresql://192.168.0.54:5432/timetracker
spring.datasource.username: admin
spring.datasource.password: admin
spring.jpa.hibernate.ddl-auto: update
---

spring:
  profiles: herokudb

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.datasource.platform: postgres
spring.datasource.url: jdbc:postgresql://192.168.0.54:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: 1234567
spring.jpa.hibernate.ddl-auto: update